### ISSUE TITLE
warning in compilation of current version of Parser.cpp

### ISSUE THREAD

**Issue by webmiche** [Superty/llvm-project#13]
I got the following warning, when compiling the current patch of @Dinistro :

home/webmiche/Desktop/ETH/llvm-project/mlir/lib/Dialect/Presburger/Parser.cpp: In member function ‘mlir::LogicalResult mlir::presburger::PresburgerSetParser::parseFlatAffineConstraints(mlir::presburger::Expr*, mlir::FlatAffineConstraints&)’:
/home/webmiche/Desktop/ETH/llvm-project/mlir/lib/Dialect/Presburger/Parser.cpp:543:74: warning: implicitly-declared ‘mlir::FlatAffineConstraints& mlir::FlatAffineConstraints::operator=(const mlir::FlatAffineConstraints&)’ is deprecated [-Wdeprecated-copy]
  543 |   cs = FlatAffineConstraints(dimNameToIndex.size(), symNameToIndex.size());
      |                                                                          ^
In file included from /home/webmiche/Desktop/ETH/llvm-project/mlir/include/mlir/Dialect/Presburger/Parser.h:9,
                 from /home/webmiche/Desktop/ETH/llvm-project/mlir/lib/Dialect/Presburger/Parser.cpp:6:
/home/webmiche/Desktop/ETH/llvm-project/mlir/include/mlir/Analysis/AffineStructures.h:110:3: note: because ‘mlir::FlatAffineConstraints’ has user-provided ‘mlir::FlatAffineConstraints::FlatAffineConstraints(const mlir::FlatAffineConstraints&)’
  110 |   FlatAffineConstraints(const FlatAffineConstraints &other);
      |   ^~~~~~~~~~~~~~~~~~~~~

**Comment by Dinistro** [comment]
I can currently not reproduce this locally. It seems like my cpp flags are still not set in an ordinary way.

**Comment by Dinistro** [comment]
After I added the missing flag to the build/build.ninja I can now reproduce this. I'm somehow not able to set cpp flags in any CMake file. Question is, why on earth is this flag set in you local development environment? It's not contained in `-Wall -Wextra -pedantic`.



To the actual issue:
According to https://stackoverflow.com/questions/51863588/warning-definition-of-implicit-copy-constructor-is-deprecated there exists a "Rule of Three":

> If a class requires a user-defined destructor, a user-defined copy constructor, or a user-defined copy assignment operator, it almost certainly requires all three.

It seems like this "rule" wasn't obeyed for `FlatAffineConstraints`, so is this intended by the MLIR team or do we use them wrong? Perhaps @tobiasgrosser has some valuable insights on this.

**Comment by tobiasgrosser** [comment]
I guess this is just a bug in MLIR. If you submit a patch to fix it, they will either agree (likely) or give you a reason why their code still makes sense.

Now, just fixing the flags you pass might be all that you really need from a practical perspective.

**Comment by Dinistro** [comment]
> If you submit a patch to fix it ...

If time permits I can do so later. At the moment there are more pressing issues.

> Now, just fixing the flags you pass might be all that you really need from a practical perspective.

Do you address @webmiche with this or me? In the later case, do you suggest any additional flags to be added? I already have `-Wall -Wextra -pedantic` and the other llvm/mlir specific flags, i.e `-fno-exceptions -fno-rtti`.

**Comment by tobiasgrosser** [comment]
In fact, it is just a warning. @webmiche could just live with it (or disable it with compiler flags)

**Comment by webmiche** [comment]
I guess I will just live with it 👍
