### ISSUE TITLE
Additional failing testcase

### ISSUE THREAD

**Issue by webmiche** [Superty/llvm-project#15]
In my PR 3 testcases, which are not from me, fail. 2 of which are the ones we already know of, the third one comes from the dialect i think. Maybe @Dinistro can take a look at it :)

**Comment by Dinistro** [comment]
Thanks for the report. 

I already fixed this bug locally where I work on the set contains functionality. This was a breaking change in mlir that changed the handling of booleans. In previous versions they were encoded as 0 and 1, now with `true` and `false`.

I could commit this small change and you could rebase again or we can wait until there is a contains prototype. What do you prefer?

**Comment by webmiche** [comment]
We can leave it like this and wait for the contains prototype i guess.
