### ISSUE TITLE
[Discussion] Piecewise Presburger Expressions syntax

### ISSUE THREAD

**Issue by Dinistro** [Superty/llvm-project#22]
As we already have a presburger.contains lowering I started working on a design for piecewise presburger expressions. 
Before I show my different ideas, lets recap the `pw_aff` syntax used in ISL and the one for `affine_map` in MLIR:

ISL:

```
[n] -> { [x] → [x + 1] : 0 ≤ x < n − 1; [x] → [0] : x = n − 1 }
```

MLIR:

```mlir
(d0, d1)[s0] -> (d0, d0 + d1 + s0)
```

First of all, I think that sticking to the dimension and symbol list syntax (the (d0, d1)[s0] in the above example) would be great, as this was consistently done till now. Therefore we should base the design on the MLIR example and extend the `affine_map` with informations about the different domains.

```mlir
(x)[n] -> (x + 1) : (0 <= x and x < n - 1); (x)[n] -> (0) : (x = n - 1)
```

Alternatively with additional parenthesis:

 ```mlir
((x)[n] -> (x + 1) : (0 <= x and x < n - 1)); ((x)[n] -> (0) : (x = n - 1))
```

Or with just one dimension and symbol list:

```mlir
(x)[n] -> (x + 1) : (0 <= x and x < n - 1) ; (0) : (x = n - 1)

// Or

(x)[n] -> ((x + 1) : (0 <= x and x < n - 1)) ; ((0) : (x = n - 1))
```

I know that all these approaches are kind of hard to read, but I'm not sure if there is any representation thats really great for so much information. As we didn't use `{}` for Presburger sets and the usage of them outside of sets could be confusing, I decided to not use them in the above drafts. 
In my opinion the second last option would be my preferred approach for now, but what do you think?

**Comment by webmiche** [comment]
```
(x)[n] -> (x + 1) : (0 <= x and x < n - 1) ; (0) : (x = n - 1)
```
Looks the best to me, as I feel like too many parenthesis are more confusing than helping and writing `(x)[n]` two times feels unnecessairy to me. Unless there are actually instances in which we want to allow for different dimensionality and symbols.

**Comment by Dinistro** [comment]
As you all agree with this design, I will start working on this next week.
