### ISSUE TITLE
Speed up Presburger test execution

### ISSUE THREAD

**Issue by Dinistro** [Superty/llvm-project#7]
I think it would be a good idea to just be able to run the presburger related tests. Currently I have to build mutliple mlir binarys that are huge if I want to execute tests. Additionally always all tests FileCheck tests are executed. Overall this takes 5 to 10 minutes. 

If we can split the tests into multiple targets, this would be nice for development speed.

**Comment by tobiasgrosser** [comment]
BUILD_SHARED_LIBS should speedup linking. Also, you should be able to llvm-lit to a path to just run a subset of the tests. Not sure, but I assume there should/could also be a make test to just test a subset, e.g., using check-mlir-dialect-presburger.

**Comment by Dinistro** [comment]
I didn't know that, thank you.  

```
ninja mlir-opt && ninja check-mlir-dialect-presburger
```

does all I need and takes like 1 minute, maybe 2. 

Edit: OK, maybe 4 to 5 as my machine is not the fastest
