### ISSUE TITLE
How to handle symbols in Presburger sets

### ISSUE THREAD

**Issue by Dinistro** [Superty/llvm-project#8]
When the prototype was created I blindly ported the symbols from `FlatAffineConstraints` to the `PresburgerSet` without much thought. Now that this prototype is growing, we should think about the semantics of symbols. Therefore I list all the facts I know of yet:

- Symbols are used to make constraints dependent on specified SSA values, e.g. memref sizes. They are constant in a region of interest. 
- From the previous, we get that we cannot eliminate the symbols during compile time as their values might be unknown. 
- They can currently only appear as constant in constraints. Changing this might complicate transformations.
- Sampling is in general impossible if we have symbols. Consider the set `(x)[s] : x >= s` and assume we do not know `s` during compile time. Note that this might also be a problem for the MLIR patch. 

**Questions / Unclarities:**

- Do we need symbols at all? I don't know now that I wrote all of this down. 
- How should we treat symbols in operations? Currently, we assert that the count of symbols for both participating sets is equal and we do not add new once to the result. 
It would perhaps make sense to have union with to following type: 
`(!presburger.set<d, s1>, !presburger.set<d,s2>) -> !presburger.set<d, s1 + s2>`

Some inputs of you @tobiasgrosser and @Superty would be much appreciated.

**Comment by tobiasgrosser** [comment]
How are symbols different to parameters in isl?

**Comment by superty** [comment]
I agree, they appear to be the same. It would probably be best to work with unparametrized sets for now.

**Comment by Dinistro** [comment]
They are, as far as I can tell, the same. The problem is that we do not know their values during evaluation and therefore some operations cannot be performed. 

Currently the symbols names are irrelevant as they are only identified by an index. This might be a problem for most operations as the semantics aren't clear. If we want to work with them we probably need to introduce a name binding. 

If we later on want to lower this, the results of operations might depend on the bounded symbol/parameter SSA value.

**Comment by tobiasgrosser** [comment]
Unparameterized sets could be a good start, if that simplifies the implementation. However, in the end we want parameterized sets, AFAIU. Questions that arise due to parameterization could be handled similarly to how isl handles them. This should also help us to determine what sample() should return in such cases.

**Comment by Dinistro** [comment]
Good point. 
I will restructure the code and add unreachable assertions to all the cases we did not yet cover. This should make it easier to find the unimplemented parts if we later start adding this functionality.

**Comment by superty** [comment]
The existing emptiness check in `FlatAffineContraints` seems to work the same way as what we are doing currently, as far as I can tell. It says the set is empty only if it is guaranteed to be empty irrespective of what the symbol values are.

Subtraction and equality for parametric sets, as well as parametric sampling (getting a function that returns a sample for any particular value of the parameters, if one exists) all depend on Parametric Integer Programming which currently has some bugs in libint. I guess I should look into these again next week.

Edit: I'm not sure what isl does when operating on two sets with different parameters. What I wrote above is for once we have two sets with the same "space" of parameters. Taking union sounds reasonable to me, but it would probably be good to check isl as well before proceeding.

**Comment by superty** [comment]
Sorry, I mixed something up. Subtraction and equality should be fine as-is.

**Comment by Dinistro** [comment]
According to the isl tutorial it checks the names of parameters in the equality test: 

```
A := [ n ] -> { A [ i ] : 0 <= i < n };
B := [ m ] -> { A [ i ] : 0 <= i < m };
A = B ; // returns false
```
As we do not capture the name of the parameters/symbols, we cannot implement this case for now in the dialect.

**Comment by tobiasgrosser** [comment]
I am not so worried about names of parameters. This can always be an additional layer. The algorithmically difficult problems which we should at least keep in mind all arise when we have a list of parameters that are just identified by their location (p_0, ..., p_n).

**Comment by Dinistro** [comment]
This issue is not relevant anymore
